Ensure the cli's test commands work
filecoin-project/curio pull request #119
Opened 2024-07-23 01:17 UTC by snadrus

This tests the `curio test window-post *` set.

2024-07-23 07:44 UTC, LexLuthr requested changes
I understand what we are testing here but I don't see why we are doing Forest setup.

2024-07-23 07:44 UTC, LexLuthr commented on cmd/curio/test-cli.go
> +			err = deps.DB.QueryRow(ctx, `SELECT task_id, result FROM harmony_test WHERE task_id IN ($1)`, taskIDs).Scan(&taskID, &result)
```suggestion
			err = deps.DB.QueryRow(ctx, `SELECT task_id, result FROM harmony_test WHERE task_id = ANY($1)`, taskIDs).Scan(&taskID, &result)
```

2024-07-23 07:44 UTC, LexLuthr commented on itests_with_chain/cli_post_test.go
> +func CliEnv() func(name string, args ...string) *CliThing {
CURIO_HARMONYDB_HOSTS needs to be set to "yugabyte" to talk to the docker container. Explains the error in failed test.

2024-07-29 22:26 UTC, snadrus commented
> I understand what we are testing here but I don't see why we are doing Forest setup.

I need to get a full Curio CLI running, so it either needs a chain server. What is the best way to do that?

2025-04-30 08:54 UTC, LexLuthr commented
Closing this as it requires complete refactor based on current code.

2025-04-30 08:54 UTC, closed without merging