Use transactions in sector migrations
filecoin-project/curio pull request #169
Opened 2024-08-23 12:52 UTC by magik6k

Also adds a simple progress print every 1000 sectors.

2024-08-26 20:46 UTC, snadrus requested changes

2024-08-26 20:46 UTC, snadrus commented on cmd/curio/guidedsetup/shared.go
> +			_, err := db.Exec(ctx, `
tx.Exec

2024-08-26 20:46 UTC, snadrus commented on cmd/curio/guidedsetup/shared.go
> +				_, err = db.Exec(ctx, `
tx.Exec

2024-10-16 11:31 UTC, LexLuthr approved these changes

2024-10-18 16:16 UTC, snadrus approved these changes

2024-10-18 16:17 UTC, merged