refactor: move network validation to GetFullNodeAPIV1Curio
filecoin-project/curio pull request #345
Opened 2024-12-10 19:00 UTC by Winter-Soren

This PR implements network validation at the API connection level to prevent mismatched network connections early in the startup process.

Changes:
1. Removed separate network validation function and use existing `build.BuildTypeString()`
2. Moved network validation from `run.go` to `GetFullNodeAPIV1Curio()`
3. Added validation for each chain node with proper error handling and logging
4. Only proceeds if at least one compatible node is found

Fixes #340

2024-12-11 10:23 UTC, LexLuthr requested changes
I think cleanup from previous approach is pending.

2024-12-11 10:23 UTC, LexLuthr commented on build/params.go
> +func CurrentNetwork() string {
We don't need this function or above constants

2024-12-11 10:23 UTC, LexLuthr commented on cmd/curio/run.go
> +		api, closer, err := lcli.GetFullNodeAPI(cctx)
I though I already clarified that we don't need this in run in the original issue

2024-12-11 10:23 UTC, LexLuthr commented on deps/apiinfo.go
> +	if len(ainfoCfg) == 0 {
~~We don't need this check~~
Ignore this.

2024-12-11 10:23 UTC, LexLuthr commented on deps/apiinfo.go
> +		return nil, nil, xerrors.Errorf("no compatible nodes found - all nodes had network mismatches or connection errors")
I don't think we need to change this message

2024-12-16 10:38 UTC, LexLuthr requested changes
Looks good. Just need 1 last change.

2024-12-16 10:38 UTC, LexLuthr commented on cmd/curio/run.go
Revert this file to its original form. There is still unused code there.

2025-01-06 07:49 UTC, LexLuthr commented
@Winter-Soren Can you please run `make gen` in the curio repo? It should fix the failing test. It might complaint about missing dependencies, please install those.

2025-01-13 09:25 UTC, LexLuthr commented
@Winter-Soren Follow up on last message. Can you please finish the PR so we can merge this?

2025-01-13 14:02 UTC, LexLuthr requested changes
Please make the following changed to allow tests to pass and fix the conflict.

2025-01-13 14:02 UTC, LexLuthr commented on cmd/curio/run.go
> +		err = rpc.ListenAndServe(ctx, dependencies, shutdownChan)
```suggestion
		err = rpc.ListenAndServe(ctx, dependencies, shutdownChan) // Monitor for shutdown.
```

2025-01-13 14:04 UTC, LexLuthr commented on deps/apiinfo.go
> +	"github.com/filecoin-project/lotus/build"
You should use the build package from Curio here.
"github.com/filecoin-project/curio/build"

2025-01-13 14:32 UTC, Winter-Soren commented on deps/apiinfo.go
> +	"github.com/filecoin-project/lotus/build"
Sure, will proceed ahead!

2025-01-13 18:30 UTC, Winter-Soren commented
@LexLuthr as suggested I have added the build package "github.com/filecoin-project/curio/build" in apiinfo.go
but its still failing.

2025-01-14 10:15 UTC, LexLuthr commented
@Winter-Soren https://app.circleci.com/pipelines/github/filecoin-project/curio/1566/workflows/bfbb7f65-b38a-4802-b754-0f0d3bfa6352/jobs/13668 will tell you why test are not passing. We group the go dependencies. Just run `make fix-imports` and commit the changes. It should fix the test.

2025-01-16 09:51 UTC, LexLuthr commented
@Winter-Soren Can we please finish this PR? Can you please make the requested changes so tests can pass?

2025-01-16 20:18 UTC, Winter-Soren commented
@LexLuthr I’ve run the make fix-imports command as suggested, and it seems that all test cases have passed.

2025-01-17 06:18 UTC, LexLuthr approved these changes

2025-01-17 06:56 UTC, merged