Mongo UI fixes
filecoin-project/curio pull request #79
Opened 2024-07-02 20:37 UTC by snadrus

- Recent Wins Needs Refreshing: every 10m

TODO:
- Sync Status Lacks a "Out of Sync" Button:
- `curio test window-post task` does not handle multiple minerIDs. 
- There is an issue with displaying or managing Cluster Task Miner IDs when dealing with multiple actors.
- Create Log File on Initialization
- Make Redeclare Faster and Not Run on a Single Thread, and mute it from the logs.

2024-07-08 10:51 UTC, magik6k commented on web/static/win-stats.mjs
> +        setTimeout(() => this.loadData(), 10 * 60 * 1000); // 10 minutes
10 min in a little high, you don't win that often, but I'd still lower this to maybe 2 minutes

2024-07-11 10:52 UTC, magik6k requested changes

2024-07-11 10:52 UTC, magik6k commented on web/static/cluster-tasks.mjs
> +customElements.define('storage-gc-stats', StorageGCStats);
This is definitely wrong

2024-07-12 15:20 UTC, LexLuthr approved these changes

2024-07-12 15:39 UTC, merged